services:
    flightradar24-feed:
        image: cwndev/flightradar24-feed:latest
        container_name: flightradar24-feed
        restart: always
        devices:
            - "/dev/bus/usb/001/003"